-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_feed (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  activity_type text NOT NULL CHECK (activity_type = ANY (ARRAY['workout_completed'::text, 'personal_record'::text, 'joined_team'::text, 'achievement_unlocked'::text])),
  workout_log_id uuid,
  team_id uuid,
  title text NOT NULL,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_feed_pkey PRIMARY KEY (id),
  CONSTRAINT activity_feed_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT activity_feed_workout_log_id_fkey FOREIGN KEY (workout_log_id) REFERENCES public.workout_logs(id)
);
CREATE TABLE public.ai_conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  team_id uuid,
  thread_id text NOT NULL,
  title text,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  last_message_at timestamp with time zone NOT NULL DEFAULT now(),
  message_count integer NOT NULL DEFAULT 0,
  phase text NOT NULL DEFAULT 'help'::text CHECK (phase = ANY (ARRAY['help'::text, 'query'::text, 'action'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT ai_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT ai_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_help_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  feedback_text text,
  was_helpful boolean,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_help_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT ai_help_feedback_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.ai_conversations(id),
  CONSTRAINT ai_help_feedback_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.ai_messages(id),
  CONSTRAINT ai_help_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])),
  content text NOT NULL,
  message_id text,
  tokens_used integer,
  cost_usd numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_messages_pkey PRIMARY KEY (id),
  CONSTRAINT ai_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.ai_conversations(id)
);
CREATE TABLE public.ai_recommendation_outcomes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recommendation_id uuid NOT NULL,
  adherence_next_week numeric,
  rating_next_week numeric,
  performance_change numeric,
  athlete_feedback text,
  outcome_quality text CHECK (outcome_quality = ANY (ARRAY['excellent'::text, 'good'::text, 'neutral'::text, 'poor'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_recommendation_outcomes_pkey PRIMARY KEY (id),
  CONSTRAINT ai_recommendation_outcomes_recommendation_id_fkey FOREIGN KEY (recommendation_id) REFERENCES public.ai_recommendations(id)
);
CREATE TABLE public.ai_recommendations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  recommendation_type text NOT NULL,
  context jsonb,
  recommendation jsonb NOT NULL,
  rationale text,
  athlete_message text,
  was_accepted boolean,
  accepted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT ai_recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_safety_rules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rule_name text NOT NULL UNIQUE,
  rule_type text NOT NULL,
  rule_value jsonb NOT NULL,
  enabled boolean DEFAULT true,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_safety_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_usage_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  endpoint text NOT NULL,
  model text NOT NULL,
  prompt_tokens integer NOT NULL,
  completion_tokens integer NOT NULL,
  total_tokens integer NOT NULL,
  estimated_cost numeric NOT NULL,
  user_id uuid,
  feature text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.content_review_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['workout_template'::text, 'drill'::text, 'training_plan'::text])),
  content_id uuid NOT NULL,
  content_data jsonb NOT NULL,
  generation_request jsonb NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_review'::text, 'approved'::text, 'rejected'::text, 'needs_revision'::text])),
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  generated_at timestamp with time zone DEFAULT now(),
  generated_by_agent text NOT NULL,
  requested_by_user_id uuid,
  requested_by_role text,
  assigned_to_coach_id uuid,
  assigned_at timestamp with time zone,
  reviewed_by_coach_id uuid,
  reviewed_at timestamp with time zone,
  coach_notes text,
  safety_rating integer CHECK (safety_rating >= 1 AND safety_rating <= 5),
  quality_rating integer CHECK (quality_rating >= 1 AND quality_rating <= 5),
  accuracy_rating integer CHECK (accuracy_rating >= 1 AND accuracy_rating <= 5),
  changes_requested ARRAY,
  validated boolean DEFAULT false,
  published_at timestamp with time zone,
  rejection_reason text,
  review_duration_minutes integer,
  revision_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_review_queue_pkey PRIMARY KEY (id),
  CONSTRAINT content_review_queue_requested_by_user_id_fkey FOREIGN KEY (requested_by_user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT content_review_queue_assigned_to_coach_id_fkey FOREIGN KEY (assigned_to_coach_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT content_review_queue_reviewed_by_coach_id_fkey FOREIGN KEY (reviewed_by_coach_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.daily_workout_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  team_id uuid,
  plan_id uuid NOT NULL,
  workout_date date NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  week_number integer NOT NULL,
  phase_name text,
  scheduled_workout jsonb NOT NULL,
  actual_workout jsonb,
  was_substituted boolean DEFAULT false,
  substitution_reason text,
  original_template_id uuid,
  substituted_template_id uuid,
  completed boolean DEFAULT false,
  completed_log_id uuid,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT daily_workout_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT daily_workout_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT daily_workout_assignments_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.training_plans(id),
  CONSTRAINT daily_workout_assignments_original_template_id_fkey FOREIGN KEY (original_template_id) REFERENCES public.workout_templates(id),
  CONSTRAINT daily_workout_assignments_substituted_template_id_fkey FOREIGN KEY (substituted_template_id) REFERENCES public.workout_templates(id),
  CONSTRAINT daily_workout_assignments_completed_log_id_fkey FOREIGN KEY (completed_log_id) REFERENCES public.workout_logs(id)
);
CREATE TABLE public.drill_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  drill_id uuid NOT NULL,
  user_id uuid NOT NULL,
  overall_rating integer NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5),
  difficulty_rating integer CHECK (difficulty_rating >= 1 AND difficulty_rating <= 5),
  effectiveness_rating integer CHECK (effectiveness_rating >= 1 AND effectiveness_rating <= 5),
  clarity_rating integer CHECK (clarity_rating >= 1 AND clarity_rating <= 5),
  review_text text,
  would_recommend boolean,
  user_experience_level text,
  completion_count integer DEFAULT 1,
  technique_improvement_noticed boolean,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT drill_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT drill_ratings_drill_id_fkey FOREIGN KEY (drill_id) REFERENCES public.drills(id),
  CONSTRAINT drill_ratings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.drills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  procedure text,
  category text NOT NULL CHECK (category = ANY (ARRAY['technique'::text, 'power'::text, 'endurance'::text, 'balance'::text, 'coordination'::text, 'racing'::text])),
  difficulty_level text DEFAULT 'intermediate'::text CHECK (difficulty_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text, 'expert'::text])),
  on_water boolean DEFAULT false,
  benefits text,
  physiological_purpose text,
  technical_focus_points ARRAY DEFAULT '{}'::text[],
  coaching_points ARRAY DEFAULT '{}'::text[],
  common_errors ARRAY DEFAULT '{}'::text[],
  progression_path ARRAY DEFAULT '{}'::text[],
  related_drills ARRAY DEFAULT '{}'::text[],
  equipment ARRAY DEFAULT '{}'::text[],
  setup_time integer,
  duration integer,
  variations jsonb DEFAULT '{}'::jsonb,
  media_urls jsonb DEFAULT '{}'::jsonb,
  validated boolean DEFAULT false,
  created_by uuid NOT NULL,
  tags ARRAY DEFAULT '{}'::text[],
  exported_at timestamp with time zone,
  source text DEFAULT 'user_created'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT drills_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erg_session_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  display_name text NOT NULL,
  device_id text,
  status text NOT NULL CHECK (status = ANY (ARRAY['ready'::text, 'active'::text, 'disconnected'::text])),
  data jsonb,
  last_heartbeat timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  group_name text,
  CONSTRAINT erg_session_participants_pkey PRIMARY KEY (id),
  CONSTRAINT erg_session_participants_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.erg_sessions(id)
);
CREATE TABLE public.erg_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  join_code text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'finished'::text])),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  active_workout jsonb,
  race_state integer DEFAULT 0,
  CONSTRAINT erg_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT erg_sessions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  instructions text,
  category text NOT NULL CHECK (category = ANY (ARRAY['dynamic_warmup'::text, 'static_stretch'::text, 'mobility'::text, 'activation'::text, 'recovery'::text])),
  target_areas ARRAY DEFAULT '{}'::text[],
  equipment ARRAY DEFAULT '{}'::text[],
  duration_seconds integer,
  difficulty_level text NOT NULL DEFAULT 'beginner'::text CHECK (difficulty_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  pre_rowing boolean DEFAULT false,
  post_rowing boolean DEFAULT false,
  rowing_specific boolean DEFAULT false,
  coaching_cues ARRAY DEFAULT '{}'::text[],
  common_errors ARRAY DEFAULT '{}'::text[],
  demonstration_video_url text,
  image_url text,
  created_by uuid,
  validated boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercises_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fitness_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  template_id uuid,
  session_name text,
  session_type text NOT NULL CHECK (session_type = ANY (ARRAY['dynamic_warmup'::text, 'cooldown'::text, 'mobility'::text, 'activation'::text])),
  started_at timestamp with time zone NOT NULL,
  completed_at timestamp with time zone,
  duration_minutes integer,
  pre_rowing_session boolean DEFAULT false,
  post_rowing_session boolean DEFAULT false,
  related_rowing_session_id uuid,
  energy_level_before integer CHECK (energy_level_before >= 1 AND energy_level_before <= 5),
  energy_level_after integer CHECK (energy_level_after >= 1 AND energy_level_after <= 5),
  body_readiness integer CHECK (body_readiness >= 1 AND body_readiness <= 5),
  completed boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fitness_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT fitness_sessions_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.fitness_templates(id)
);
CREATE TABLE public.fitness_template_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  order_in_template integer NOT NULL,
  duration_seconds integer,
  repetitions integer,
  each_side boolean DEFAULT false,
  rest_after_seconds integer DEFAULT 0,
  notes text,
  coaching_emphasis text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fitness_template_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_template_exercises_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.fitness_templates(id),
  CONSTRAINT fitness_template_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.fitness_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  objective text,
  template_type text NOT NULL CHECK (template_type = ANY (ARRAY['dynamic_warmup'::text, 'cooldown'::text, 'mobility'::text, 'activation'::text])),
  estimated_duration_minutes integer NOT NULL,
  min_duration_minutes integer,
  max_duration_minutes integer,
  difficulty_level text NOT NULL DEFAULT 'beginner'::text CHECK (difficulty_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  equipment_required ARRAY DEFAULT '{}'::text[],
  equipment_optional ARRAY DEFAULT '{}'::text[],
  home_friendly boolean DEFAULT true,
  pre_rowing boolean DEFAULT false,
  post_rowing boolean DEFAULT false,
  rowing_rest_day boolean DEFAULT false,
  workout_intensity text CHECK (workout_intensity = ANY (ARRAY['light'::text, 'moderate'::text, 'intense'::text])),
  when_to_use text,
  benefits ARRAY DEFAULT '{}'::text[],
  validated boolean DEFAULT false,
  user_rating numeric,
  created_by uuid,
  tags ARRAY DEFAULT '{}'::text[],
  source text DEFAULT 'user_created'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fitness_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.generated_workout_candidates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_plan_id uuid,
  generated_by_user_id uuid,
  workout_description text NOT NULL,
  workout_type text NOT NULL,
  intensity_zone text,
  duration_minutes integer,
  coaching_notes text,
  generation_context jsonb NOT NULL DEFAULT '{}'::jsonb,
  times_generated integer DEFAULT 1,
  times_completed integer DEFAULT 0,
  completion_rate numeric DEFAULT 
CASE
    WHEN (times_generated > 0) THEN (((times_completed)::numeric / (times_generated)::numeric) * (100)::numeric)
    ELSE (0)::numeric
END,
  average_rating numeric,
  rating_count integer DEFAULT 0,
  status text NOT NULL DEFAULT 'candidate'::text CHECK (status = ANY (ARRAY['candidate'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'duplicate'::text, 'promoted'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  promoted_to_template_id uuid,
  similar_to_template_id uuid,
  similarity_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT generated_workout_candidates_pkey PRIMARY KEY (id),
  CONSTRAINT generated_workout_candidates_source_plan_id_fkey FOREIGN KEY (source_plan_id) REFERENCES public.training_plans(id),
  CONSTRAINT generated_workout_candidates_generated_by_user_id_fkey FOREIGN KEY (generated_by_user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT generated_workout_candidates_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT generated_workout_candidates_promoted_to_template_id_fkey FOREIGN KEY (promoted_to_template_id) REFERENCES public.workout_templates(id),
  CONSTRAINT generated_workout_candidates_similar_to_template_id_fkey FOREIGN KEY (similar_to_template_id) REFERENCES public.workout_templates(id)
);
CREATE TABLE public.pacing_recommendations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  workout_zone text NOT NULL CHECK (workout_zone = ANY (ARRAY['UT2'::text, 'UT1'::text, 'AT'::text, 'TR'::text, 'AN'::text])),
  workout_date date NOT NULL,
  split_min numeric NOT NULL,
  split_max numeric NOT NULL,
  split_target numeric NOT NULL,
  hr_min integer,
  hr_max integer,
  spm_range text,
  rpe_range text,
  confidence_level text NOT NULL CHECK (confidence_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  data_sources ARRAY NOT NULL DEFAULT '{}'::text[],
  recommendation_basis text,
  baseline_adjustment numeric DEFAULT 0,
  zone_history_adjustment numeric DEFAULT 0,
  cross_zone_adjustment numeric DEFAULT 0,
  total_adjustment numeric DEFAULT 0,
  user_override_split numeric,
  user_override_reason text,
  user_override_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pacing_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT pacing_recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.plan_adaptations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL,
  week_number integer NOT NULL,
  proposed_at timestamp with time zone DEFAULT now(),
  proposed_by text DEFAULT 'system'::text,
  adaptation_type text NOT NULL CHECK (adaptation_type = ANY (ARRAY['reduce_volume'::text, 'add_recovery'::text, 'swap_workout'::text, 'extend_phase'::text, 'reduce_intensity'::text])),
  reasoning text NOT NULL,
  changes jsonb NOT NULL,
  analysis_data jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'modified'::text, 'coach_review'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  applied_at timestamp with time zone,
  coach_modifications jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT plan_adaptations_pkey PRIMARY KEY (id),
  CONSTRAINT plan_adaptations_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.training_plans(id),
  CONSTRAINT plan_adaptations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.plan_phases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL,
  phase_name text NOT NULL CHECK (phase_name = ANY (ARRAY['Base Building'::text, 'Build'::text, 'Peak'::text, 'Taper'::text, 'Maintenance'::text, 'Recovery'::text])),
  phase_number integer NOT NULL CHECK (phase_number >= 1 AND phase_number <= 6),
  start_week integer NOT NULL CHECK (start_week >= 1),
  end_week integer NOT NULL CHECK (end_week >= 1),
  training_focus text,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT plan_phases_pkey PRIMARY KEY (id),
  CONSTRAINT plan_phases_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.training_plans(id)
);
CREATE TABLE public.plan_weeks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL,
  week_number integer NOT NULL CHECK (week_number >= 1),
  phase_id uuid,
  week_start_date date NOT NULL,
  week_end_date date NOT NULL,
  weekly_volume_target integer,
  weekly_volume_actual integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT plan_weeks_pkey PRIMARY KEY (id),
  CONSTRAINT plan_weeks_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.training_plans(id),
  CONSTRAINT plan_weeks_phase_id_fkey FOREIGN KEY (phase_id) REFERENCES public.plan_phases(id)
);
CREATE TABLE public.plan_workouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL,
  week_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  workout_date date NOT NULL,
  workout_template_id uuid,
  workout_order integer DEFAULT 1 CHECK (workout_order >= 1),
  custom_notes text,
  is_completed boolean DEFAULT false,
  completed_log_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  drill_id uuid,
  CONSTRAINT plan_workouts_pkey PRIMARY KEY (id),
  CONSTRAINT plan_workouts_drill_id_fkey FOREIGN KEY (drill_id) REFERENCES public.drills(id),
  CONSTRAINT plan_workouts_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.training_plans(id),
  CONSTRAINT plan_workouts_week_id_fkey FOREIGN KEY (week_id) REFERENCES public.plan_weeks(id),
  CONSTRAINT plan_workouts_workout_template_id_fkey FOREIGN KEY (workout_template_id) REFERENCES public.workout_templates(id),
  CONSTRAINT plan_workouts_completed_log_id_fkey FOREIGN KEY (completed_log_id) REFERENCES public.workout_logs(id)
);
CREATE TABLE public.strength_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  placeholder_column text DEFAULT 'future_expansion'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT strength_exercises_pkey PRIMARY KEY (id)
);
CREATE TABLE public.strength_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  placeholder_column text DEFAULT 'future_expansion'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT strength_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['member'::text, 'captain'::text, 'coach'::text])),
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL CHECK (length(name) >= 3 AND length(name) <= 100),
  description text,
  invite_code text NOT NULL UNIQUE CHECK (length(invite_code) = 8),
  coach_id uuid NOT NULL,
  max_members integer NOT NULL DEFAULT 50 CHECK (max_members > 0),
  is_public boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teams_pkey PRIMARY KEY (id)
);
CREATE TABLE public.template_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  user_id uuid NOT NULL,
  overall_rating integer NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5),
  difficulty_rating integer CHECK (difficulty_rating >= 1 AND difficulty_rating <= 5),
  effectiveness_rating integer CHECK (effectiveness_rating >= 1 AND effectiveness_rating <= 5),
  clarity_rating integer CHECK (clarity_rating >= 1 AND clarity_rating <= 5),
  review_text text,
  would_recommend boolean,
  user_experience_level text,
  completion_count integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT template_ratings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.template_usage_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  user_id uuid,
  event_type text NOT NULL,
  session_id uuid,
  user_experience_level text,
  device_type text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_usage_events_pkey PRIMARY KEY (id),
  CONSTRAINT template_usage_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.training_plan_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL,
  user_id uuid NOT NULL,
  overall_rating integer NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5),
  structure_rating integer CHECK (structure_rating >= 1 AND structure_rating <= 5),
  progression_rating integer CHECK (progression_rating >= 1 AND progression_rating <= 5),
  clarity_rating integer CHECK (clarity_rating >= 1 AND clarity_rating <= 5),
  review_text text,
  would_recommend boolean,
  user_experience_level text,
  completion_percentage integer CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  goal_achieved boolean,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT training_plan_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT training_plan_ratings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.training_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  team_id uuid,
  assigned_by uuid,
  name text NOT NULL,
  goal text NOT NULL,
  plan_data jsonb NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  weeks_duration integer NOT NULL,
  hours_per_week numeric NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'paused'::text, 'replaced'::text, 'archived'::text])),
  current_week integer DEFAULT 1,
  completion_percentage integer DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  original_plan_id uuid,
  modification_reason text,
  generation_job_id uuid,
  generation_context jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  activated_at timestamp with time zone,
  completed_at timestamp with time zone,
  workouts_extracted boolean DEFAULT false,
  plan_type text DEFAULT 'generated'::text CHECK (plan_type = ANY (ARRAY['generated'::text, 'custom'::text, 'template'::text])),
  CONSTRAINT training_plans_pkey PRIMARY KEY (id),
  CONSTRAINT training_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT training_plans_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT training_plans_original_plan_id_fkey FOREIGN KEY (original_plan_id) REFERENCES public.training_plans(id),
  CONSTRAINT training_plans_generation_job_id_fkey FOREIGN KEY (generation_job_id) REFERENCES public.content_review_queue(id)
);
CREATE TABLE public.user_baseline_metrics (
  user_id uuid NOT NULL,
  pr_2k_time numeric,
  pr_2k_date date,
  pr_2k_split numeric,
  pr_6k_time numeric,
  pr_6k_date date,
  pr_6k_split numeric,
  pr_500m_time numeric,
  pr_500m_date date,
  pr_10k_time numeric,
  pr_10k_date date,
  estimated_hr_max integer CHECK (estimated_hr_max >= 100 AND estimated_hr_max <= 220),
  hr_max_source text CHECK (hr_max_source = ANY (ARRAY['tested'::text, 'formula'::text, 'manual'::text])),
  hr_max_date date,
  fitness_level text CHECK (fitness_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  test_history jsonb DEFAULT '[]'::jsonb,
  pr_2k_watts integer,
  CONSTRAINT user_baseline_metrics_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_baseline_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  feedback_type text NOT NULL CHECK (feedback_type = ANY (ARRAY['bug'::text, 'feature'::text, 'other'::text])),
  message text NOT NULL,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'reviewed'::text, 'resolved'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  admin_response text,
  admin_response_at timestamp with time zone,
  CONSTRAINT user_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT user_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_goals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['weekly_distance'::text, 'weekly_time'::text, 'weekly_sessions'::text, 'benchmark_goal'::text])),
  target_value numeric NOT NULL,
  start_date timestamp with time zone DEFAULT now(),
  deadline timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metric_key text,
  CONSTRAINT user_goals_pkey PRIMARY KEY (id),
  CONSTRAINT user_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_integrations (
  user_id uuid NOT NULL,
  google_sheet_id text,
  last_export_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  concept2_token text,
  concept2_refresh_token text,
  concept2_expires_at timestamp with time zone,
  concept2_user_id text,
  CONSTRAINT user_integrations_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  display_name text NOT NULL,
  email text,
  avatar_url text,
  bio text,
  rowing_sides text,
  skill_level text DEFAULT 'novice'::text CHECK (skill_level = ANY (ARRAY['novice'::text, 'recreational'::text, 'competitive'::text, 'elite'::text])),
  rowing_experience_years integer,
  birth_year integer,
  gender text,
  height_cm integer,
  weight_kg integer,
  steady_state_duration integer DEFAULT 45,
  points_goal_percentage integer DEFAULT 100,
  plan_start_date date,
  start_date date,
  roles ARRAY DEFAULT ARRAY['athlete'::text],
  baseline_tests jsonb DEFAULT '{}'::jsonb,
  personal_records jsonb DEFAULT '{}'::jsonb,
  profile_visibility text DEFAULT 'public'::text CHECK (profile_visibility = ANY (ARRAY['public'::text, 'friends'::text, 'private'::text])),
  share_workouts boolean DEFAULT true,
  share_progress boolean DEFAULT true,
  total_workouts integer DEFAULT 0,
  total_distance_meters bigint DEFAULT 0,
  total_time_minutes integer DEFAULT 0,
  current_streak_days integer DEFAULT 0,
  longest_streak_days integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_active_at timestamp with time zone DEFAULT now(),
  exported_at timestamp with time zone,
  source text DEFAULT 'supabase'::text,
  coach_level text CHECK (coach_level = ANY (ARRAY['junior'::text, 'standard'::text, 'senior'::text, 'master'::text])),
  certifications jsonb DEFAULT '[]'::jsonb,
  specializations ARRAY DEFAULT ARRAY[]::text[],
  years_coaching integer CHECK (years_coaching IS NULL OR years_coaching >= 0 AND years_coaching <= 80),
  validation_stats jsonb DEFAULT '{"approved_count": 0, "rejected_count": 0, "revision_count": 0, "total_reviewed": 0, "average_review_time_minutes": 0}'::jsonb,
  preferences jsonb DEFAULT '{}'::jsonb,
  max_heart_rate integer,
  resting_heart_rate integer,
  weight_lbs integer,
  birth_date date,
  benchmark_preferences jsonb DEFAULT '{}'::jsonb,
  daily_recommendation jsonb,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workout_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  template_id uuid,
  workout_name text NOT NULL,
  workout_type text NOT NULL,
  completed_at timestamp with time zone NOT NULL,
  duration_minutes integer,
  distance_meters integer,
  calories_burned integer,
  average_heart_rate integer,
  max_heart_rate integer,
  average_stroke_rate integer,
  notes text,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  training_zone text CHECK (training_zone = ANY (ARRAY['UT2'::text, 'UT1'::text, 'AT'::text, 'TR'::text, 'AN'::text])),
  avg_split_500m numeric,
  perceived_exertion integer CHECK (perceived_exertion >= 1 AND perceived_exertion <= 10),
  external_id text UNIQUE,
  source text DEFAULT 'concept2'::text,
  raw_data jsonb,
  watts integer,
  duration_seconds numeric,
  zone_distribution jsonb DEFAULT '{}'::jsonb,
  canonical_name text,
  CONSTRAINT workout_logs_pkey PRIMARY KEY (id),
  CONSTRAINT workout_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.workout_power_distribution (
  workout_id uuid NOT NULL,
  buckets jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_power_distribution_pkey PRIMARY KEY (workout_id),
  CONSTRAINT workout_power_distribution_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workout_logs(id)
);
CREATE TABLE public.workout_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL,
  workout_type text NOT NULL,
  technique_focus ARRAY,
  coaching_points ARRAY,
  pacing_guidance text,
  estimated_duration integer,
  distance integer,
  difficulty_level text DEFAULT 'intermediate'::text,
  is_steady_state boolean DEFAULT false,
  is_test boolean DEFAULT false,
  is_interval boolean DEFAULT false,
  usage_count integer DEFAULT 0,
  completion_rate numeric DEFAULT 0.00,
  average_rating numeric DEFAULT 0.00,
  rating_count integer DEFAULT 0,
  status text DEFAULT 'published'::text,
  validated boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  training_zone text CHECK (training_zone = ANY (ARRAY['UT2'::text, 'UT1'::text, 'AT'::text, 'TR'::text, 'AN'::text])),
  workout_category text CHECK (workout_category IS NULL OR (workout_category = ANY (ARRAY['test'::text, 'interval_vo2max'::text, 'interval_threshold'::text, 'interval_mixed'::text, 'steady_state'::text, 'low_rate_progression'::text, 'warmup'::text, 'cooldown'::text, 'technical'::text, 'cross_training'::text]))),
  signature_workout text UNIQUE,
  tags ARRAY DEFAULT '{}'::text[],
  workout_structure jsonb,
  CONSTRAINT workout_templates_pkey PRIMARY KEY (id)
);